exports.level = require('./level')
exports.tempjogo = require('./tempjogo')
exports.register = require('./register')
exports.reminder = require('./reminder')
exports.premium = require('./premium')
exports.loader = require('./loader')
exports.messages = require('./messages')
exports.afk = require('./afk')